from bs4 import BeautifulSoup
import os

# Style rules for these translations:
#
# 0) Initials are not followed by a period (deviation from reference).
# 1) 'Corp' is followed by a period.
# 2) 'Inc' is followed by a period.
# 3) 'Ltd' is followed by a period.
# 4) 'Dr' is followed by a period.
#
# Reference: The Canadian Style – https://www.btb.termiumplus.gc.ca/tcdnstyl-chap?lang=eng&lettr=chapsect1&info0=1


tag_translations = \
    {
        "$20-Starbucks-test": "$20 Starbucks test",
        "1/f-noise": "1/f noise",
        "123D-Circuits": "123D Circuits",
        "15mm-slide-rail": "15mm slide rail",
        "2D-barcode": "2D barcode",
        "2D-plotting": "2D plotting",
        "2d": "2D",
        "3-minutes": "3 minutes",
        "3-volt-logic": "3 Volt logic",
        "305-RAMAC": "305 RAMAC",
        "33-RPM-record": "33 RPM record",
        "360-degree video": "360 degree video",
        "360 video": "360 degree video",
        "3-D": "3D",
        "3D-Studio": "Autodesk 3D Studio",
        "3D-input": "3D input",
        "3D-massing": "3D massing",
        "3D-projection": "3D projection",
        "3D-viewing": "3D viewing",
        "3d": "3D",
        "45-RPM-record": "45 RPM record",
        "4625-kHz": "4625 kHz",
        "5-volt-logic": "5 Volt logic",
        "5-whys": "5 whys",
        "6-Mix": "6 Mix",
        "68-Katy": "68 Katy",
        "7-segment-display": "7-segment display",
        "7400-series": "7400 series",
        "78-RPM-record": "78 RPM record",
        "787-Dreamliner": "787 Dreamliner",
        "868-MHz": "868 MHz",
        "900-MHz": "900 MHz",
        "99%-Conference": "99% Conference",

        "abandoned-railway": "abandoned railway",
        "acceleration-sensor": "acceleration sensor",
        "acetylcholine-receptor": "acetylcholine receptor",
        "acoustic-cloaking-device": "acoustic cloaking device",
        "acoustic-panel": "acoustic panel",
        "active-RFID-tag": "active RFID tag",
        "active-filter": "active filter",
        "activity-tracking": "activity tracking",
        "acute-respiratory-distress-syndrome": "acute respiratory distress syndrome",
        "ad-campaign": "ad campaign",
        "adafruit": "Adafruit Industries",
        "adaptive-word-prediction": "adaptive word prediction",
        "address-bus": "address bus",
        "adjustable-negative-voltage-regulator": "adjustable negative voltage regulator",
        "adjustable-voltage-regulator": "adjustable voltage regulator",
        "adobe": "Adobe",
        "adsr": "ADSR",
        "aerial-map": "aerial map",
        "affective-computing": "affective computing",
        "air-traffic-control": "air traffic control",
        "alarm-call": "alarm call",
        "albino-squirrel": "albino squirrel",
        "alexander-graham-bell": "Alexander Graham Bell",
        "algebraic-equation": "algebraic equation",
        "alpha-particle": "alpha particle",
        "alpha-radiation": "alpha radiation",
        "alternate-side-parking": "alternate side parking",
        "amateur-radio": "amateur radio",
        "ambient-noise": "ambient noise",
        "ambient-sound": "ambient sound",
        "amiga": "Amiga",
        "analog-circuit": "analog circuit",
        "analog-design": "analog design",
        "analog-filter": "analog filter",
        "analog-multiplier": "analog multiplier",
        "analog-synthesis": "analog synthesis",
        "analog-synthesizer": "analog synthesizer",
        "analogue-ribbon-synthesizer": "analogue ribbon synthesizer",
        "animal-language": "animal language",
        "app-album": "app album",
        "apple": "Apple Inc.",
        "apple-i": "Apple I",
        "apple-iie": "Apple IIe",
        "apple-iigs": "Apple IIGS",
        "appletv": "Apple TV",
        "application-note": "application note",
        "arbitrary-waveform-generator": "arbitrary waveform generator",
        "architectural-acoustics": "architectural acoustics",
        "architecure": "architecture",
        "arcus-cloud": "arcus cloud",
        "arduino": "Arduino",
        "artificial-brain": "artificial brain",
        "artificial-synapse": "artificial synapse",
        "assembly-language": "assembly language",
        "asset-tracking": "asset tracking",
        "atari": "Atari",
        "atmel": "Atmel",
        "atmospheric-monitoring": "atmospheric monitoring",
        "atomic-bomb": "atomic bomb",
        "atomic-clock": "atomic clock",
        "atomic-mass": "atomic mass",
        "atomic-mass-unit": "atomic mass unit",
        "attractive-fixed-set": "attractive fixed set",
        "audio-ADC": "audio ADC",
        "audio-cable": "audio cable",
        "automated-production": "automated production",
        "autonomous-sensory-meridian-response": "autonomous sensory meridian response",
        "autonomous-vehicle": "autonomous vehicle",
        "auxiliary-power-unit": "auxiliary power unit",
        "avr": "AVR",
        "A-C-Fischer": "A C Fischer",
        "A-D-Smith": "A D Smith",
        "A-Delin": "A Delin",
        "A-Farewell-to-Kings": "A Farewell to Kings",
        "A-Forest": "A Forest",
        "A-Mathematical-Theory-of-Communication": "A Mathematical Theory of Communication",
        "A-Paussa": "A Paussa",
        "A-Spacecraft-for-All": "A Spacecraft for All",
        "A-Zettl": "A Zettl",
        "AC-series-current-rating": "AC series current rating",
        "AI-Class": "AI Class",
        "ANALOG-SEEKrets": "ANALOG SEEKrets",
        "ANSI-art": "ANSI art",
        "ARM-Cortex-M0+": "ARM Cortex-M0+",
        "ARNOLDSCHE-Art-Publishers": "ARNOLDSCHE Art Publishers",
        "ARPAnet": "ARPANET",
        "ASsistive-Text-EditoR": "ASsistive Text EditoR",
        "AVR-Studio": "AVR Studio",
        "Aaron-Kemmer": "Aaron Kemmer",
        "Aaron-Souppouris": "Aaron Souppouris",
        "Aaron-Straup-Cope": "Aaron Straup-Cope",
        "Aaron-Strout": "Aaron Strout",
        "Aaron-Swartz": "Aaron Swartz",
        "Aboriginal-Peoples-Television-Network": "Aboriginal Peoples Television Network",
        "Abraham-Lincoln": "Abraham Lincoln",
        "Accordion-Guy": "Accordion Guy",
        "Ad-Kerkhof": "Ad Kerkhof",
        "Adafruit": "Adafruit Industries",
        "Adam-Carlson": "Adam Carlson",
        "Adam-Caudill": "Adam Caudill",
        "Adam-Cheyer": "Adam Cheyer",
        "Adam-Clark-Estes": "Adam Clark Estes",
        "Adam-Dunkels": "Adam Dunkels",
        "Adam-Fabio": "Adam Fabio",
        "Adam-Mann": "Adam Mann",
        "Adam-Rosen": "Adam Rosen",
        "Adobe-After-Effects": "Adobe After Effects",
        "Adobe-Creative-Suite": "Adobe Creative Suite",
        "Adobe-Creative-Suite-2": "Adobe Creative Suite 2",
        "Adobe-Illustrator": "Adobe Illustrator",
        "Adobe_Flash": "Adobe Flash",
        "Adolf-Hitler": "Adolf Hitler",
        "Adrian-J-Cotterill": "Adrian J Cotterill",
        "Adrian-Lamo": "Adrian Lamo",
        "Adrian-Marshall": "Adrian Marshall",
        "Advanced-Ground-Information-Systems": "Advanced Ground Information Systems",
        "Adventure-Lab": "Adventure Lab",
        "Adventures-with-the-Estrogen-Army": "Adventures with the Estrogen Army",
        "Advertising-Age": "Advertising Age",
        "After-Effects": "Adobe After Effects",
        "Air-France": "Air France",
        "Air-India": "Air India",
        "Air-National-Guard": "Air National Guard",
        "Airstream-trailer": "Airstream trailer",
        "Ajai-Raj": "Ajai Raj",
        "Ajit-Pardasani": "Ajit Pardasani",
        "Akin-Fernandez": "Akin Fernandez",
        "Akito-Y-Kawahara": "Akito Y Kawahara",
        "Akustica-Inc.": "Akustica Inc.",
        "Al-Gore": "Al Gore",
        "Al-Jazeera": "Al Jazeera",
        "Al-Maitland": "Al Maitland",
        "Alan-Blankman": "Alan Blankman",
        "Alan-Burlison": "Alan Burlison",
        "Alan-Guth": "Alan Guth",
        "Alan-Henry": "Alan Henry",
        "Alan-Levinovitz": "Alan Levinovitz",
        "Alan-Skorkin": "Alan Skorkin",
        "Alan-Turing": "Alan Turing",
        "Alan-Watts": "Alan Watts",
        "Alan-Wilder": "Alan Wilder",
        "Alasdair-Allan": "Alasdair Allan",
        "Alaska-Volcano-Observatory": "Alaska Volcano Observatory",
        "Albert-Camus": "Albert Camus",
        "Albert-Michelson": "Albert Michelson",
        "Alberto-Bielsa": "Alberto Bielsa",
        "Aleksandr-Lyapunov": "Aleksandr Lyapunov",
        "Alessandro-Pisa": "Alessandro Pisa",
        "Alex-Haro": "Alex Haro",
        "Alex-Heath": "Alex Heath",
        "Alex-Howard": "Alex Howard",
        "Alex-Patterson": "Alex Patterson",
        "Alex-Rivera": "Alex Rivera",
        "Alex-Ronan": "Alex Ronan",
        "Alex-Valentino": "Alex Valentino",
        "Alexander-Avtanski": "Alexander Avtanski",
        "Alexander-Belchenko": "Alexander Belchenko",
        "Alexander-George": "Alexander George",
        "Alexander-Graham-Bell": "Alexander Graham Bell",
        "Alexander-Porter": "Alexander Porter",
        "Alexander-Volkov": "Alexander Volkov",
        "Alexandra-Ossola": "Alexandra Ossola",
        "Alexey-Polilov": "Alexey Polilov",
        "Alexis-Rossi": "Alexis Rossi",
        "Alexsei-Kosygin": "Alexsei Kosygin",
        "Alfred-Holden": "Alfred Holden",
        "Alicia-J-Hotovec-Ellis": "Alicia J Hotovec-Ellis",
        "Allen-Institute-for-Artificial-Intelligence": "Allen Institute for Artificial Intelligence",
        "Allied-Electronics": "Allied Electronics",
        "Ally-McCabe": "Ally McCabe",
        "Altera-Cyclone-IV": "Altera Cyclone IV",
        "Amanda-Grant": "Amanda Grant",
        "Amar-G-Bose": "Amar G Bose",
        "Amber-Frost": "Amber Frost",
        "Amber-Williams": "Amber Williams",
        "America's-Cup": "America's Cup",
        "American-Civil-War": "American Civil War",
        "American-Institute-of-Electrical-Engineers": "American Institute of Electrical Engineers",
        "American-Physical-Society": "American Physical Society",
        "American-Standard": "American Standard",
        "Ami-Angelowicz": "Ami Angelowicz",
        "Amiga-1200": "Amiga 1200",
        "Amiga-2000": "Amiga 2000",
        "Amiga-500": "Amiga 500",
        "Amiga-Kickstart": "Amiga Kickstart",
        "Amiga-Video-Toaster": "Amiga Video Toaster",
        "Amy-Goodman": "Amy Goodman",
        "Amy-Millan": "Amy Millan",
        "Amy-Shira-Teitel": "Amy Shira Teitel",
        "An-Honest-Liar": "An Honest Liar",
        "Analog-Wire": "Analog Wire",
        "Anant-Agarwal": "Anant Agarwal",
        "Anaonda": "Anaconda",
        "Anders-Brevik": "Anders Brevik",
        "Andre-Luiten": "Andre N Luiten",
        "Andre-N-Luiten": "Andre N Luiten",
        "Andreas-Sulzer": "Andreas Sulzer",
        "Andreas-Velten": "Andreas Velten",
        "Andreas-Önnerfors": "Andreas Önnerfors",
        "Andrei-Linde": "Andrei Linde",
        "Andrew-Blankstein": "Andrew Blankstein",
        "Andrew-Cash": "Andrew Cash",
        "Andrew-Cunningham": "Andrew Cunningham",
        "Andrew-Kilpatrick": "Andrew Kilpatrick",
        "Andrew-Marmery": "Andrew Marmery",
        "Andrew-Mayeda": "Andrew Mayeda",
        "Andrew-Ng": "Andrew Ng",
        "Andrew-Robinson": "Andrew Robinson",
        "Andrew-Tate": "Andrew Tate",
        "Andrew-Webster": "Andrew Webster",
        "Andrew_Huang": "Andrew Bunnie Huang",
        "André-Christoffer-Andersen": "André Christoffer Andersen",
        "Andrés-Padilla-Domene": "Andrés Padilla Domene",
        "Andy-Coghlan": "Andy Coghlan",
        "Andy-Hertzfeld": "Andy Hertzfeld",
        "Andy-Markowitz": "Andy Markowitz",
        "Andy-Williamson": "Andy Williamson",
        "Angela-Hennessy": "Angela Hennessy",
        "Angstrom-Designs": "Angstrom Designs",
        "Ankita D. Jain": "Ankita D Jain",
        "Anna-Bressanin": "Anna Bressanin",
        "Anna-Maria_Hefele": "Anna Maria Hefele",
        "Anne-Carlisle": "Anne Carlisle",
        "Annie-Jump-Cannon": "Annie Jump Cannon",
        "Antanas-Mockus": "Antanas Mockus",
        "Anthea-Quay": "Anthea Quay",
        "Anthony-Grafton": "Anthony Grafton",
        "Antoine-Vignau": "Antoine Vignau",
        "Anwar-Congo": "Anwar Congo",
        "Apollo-17": "Apollo 17",
        "Apollo-Saturn-V": "Apollo Saturn V",
        "Apple-///": "Apple III",
        "Apple-///-Ready-to-Run": "Apple III Ready to Run",
        "Apple-DOS": "Apple DOS",
        "Apple-Extended-Keyboard": "Apple Extended Keyboard",
        "Apple-HD20": "Apple HD20",
        "Apple-I": "Apple I",
        "Apple-II-Scans": "Apple II Scans",
        "Apple IIgs": "Apple_IIGS",
        "Apple-IIGS": "Apple IIGS",
        "Apple-III": "Apple III",
        "Apple-Integer-BASIC": "Apple Integer BASIC",
        "Apple-Pugetsound-Program-Library-Exchange": "Apple Pugetsound Program Library Exchange",
        "Apple-Remote-Desktop": "Apple Remote Desktop",
        "Apple-TV": "Apple TV",
        "Apple-remote": "Apple remote",
        "Apple_IIgs": "Apple IIGS",
        "Archaeology-Magazine": "Archaeology Magazine",
        "Archbishop-Desmond-Tutu": "Archbishop Desmond Tutu",
        "Architecture-&-Design": "Architecture & Design",
        "Arduino-Arts": "Arduino Arts",
        "Arduino-IDE": "Arduino IDE",
        "Arduino-Uno": "Arduino Uno",
        "Arduino-Uno-R3": "Arduino Uno R3",
        "Arduino-compatible": "Arduino compatible",
        "Arduino_UNO": "Arduino Uno",
        "Arduino UNO": "Arduino Uno",
        "Auruino": "Arduino",
        "Area-51": "Area 51",
        "Arizona-State-University": "Arizona State University",
        "Arno-Penzias": "Arno Penzias",
        "Arnold-Wilkins": "Arnold Wilkins",
        "Arpanet": "ARPANET",
        "Art-Institute-of-Chicago": "Art Institute of Chicago",
        "Art-of-Noise": "Art of Noise",
        "Arthur C. Clarke": "Arthur C Clarke",
        "Arthur-Elgort": "Arthur Elgort",
        "Arthur-Koestler": "Arthur Koestler",
        "As-It-Happens": "As It Happens",
        "As-it-Happens": "As It Happens",
        "Asaf Even chen": "Asaf Even-Chen",
        "Ashe-Dryden": "Ashe Dryden",
        "Asher-Wolf": "Asher Wolf",
        "Ashish-Kumar": "Ashish Kumar",
        "Assistive-Contextually-Aware-Toolkit": "Assistive Contextually Aware Toolkit",
        "Association-for-Computing-Machinery": "Association for Computing Machinery",
        "Atanasoff-Berry-computer": "Atanasoff-Berry computer",
        "Atari-2600": "Atari 2600",
        "Ataturk-Cultural-Centre": "Ataturk Cultural Centre",
        "Atomic-Energy-Commission": "Atomic Energy Commission",
        "Aubrey-Kagan": "Aubrey Kagan",
        "Audio-Engineers-Society": "Audio Engineering Society",
        "Augmenting-Human-Intellect": "Augmenting Human Intellect",
        "Auguste-Choisy": "Auguste Choisy",
        "Austin-Fowler": "Austin Fowler",
        "Austin-Wilson": "Austin Wilson",
        "Autodesk-3D-Studio": "Autodesk 3D Studio",
        "Aviation-Safety-Network": "Aviation Safety Network",
        "Avro-Arrow": "Avro Arrow",
        "AVRO": "Avro",
        "AVRO Canada": "Avro Canada",

        "back-issue": "back issue",
        "bad-idea": "bad idea",
        "ball-lightning": "ball lightning",
        "B&B-Electronics": "B&B Electronics",
        "B. Jack Copeland": "B Jack Copeland",
        "BASIC-Stamp": "BASIC Stamp",
        "BBC-Horizon": "BBC Horizon",
        "BBC-Radio": "BBC Radio",
        "BBC-Radio-4": "BBC Radio 4",
        "BBC-Radio-6": "BBC Radio 6",
        "BBC-Radiophonic-Workshop": "BBC Radiophonic Workshop",
        "BSD-license": "BSD license",
        "Background-Imaging-of-Cosmic-Extragalactic-Polarization": "Background Imaging of Cosmic Extragalactic Polarization",
        "Bad-Astronomy": "Bad Astronomy",
        "Baddies-in-books": "Baddies in books",
        "Badusb": "BadUSB",
        "Banbury-sheets": "Banbury sheets",
        "Barack-Obama": "Barack Obama",
        "Barbara-Wade": "Barbara Wade",
        "Barnaby-Jack": "Barnaby Jack",
        "Barry-A-Cipra": "Barry A Cipra",
        "Barry-Siegel": "Barry Siegel",
        "Barry-Silverman": "Barry Silverman",
        "Barry-Truax": "Barry Truax",
        "Barton-Gellman": "Barton Gellman",
        "Bass-Station": "Bass Station",
        "Bath-Academy-of-Art": "Bath Academy of Art",
        "Bathurst-Street": "Bathurst Street",
        "Battleship-Island": "Battleship Island",
        "Baudoinia-compniacensis": "Baudoinia compniacensis",
        "Bayesian-method": "Bayesian method",
        "Beautiful-Evidence": "Beautiful Evidence",
        "Bebe-Barron": "Bebe Barron",
        "Bebe-Brown": "Bebe Brown",
        "Becky-Oskin": "Becky Oskin",
        "Bedroom-Producers-Blog": "Bedroom Producers Blog",
        "Bee-Media": "Bee Media",
        "Behance-Network": "Behance Network",
        "Beijing-Capital-International-Airport": "Beijing Capital International Airport",
        "Bell Labs": "Bell Telephone Laboratories",
        "Bell Laboratories": "Bell Telephone Laboratories",
        "Bell-System-Technical-Journal": "Bell System Technical Journal",
        "Belle-and-Sebastian": "Belle and Sebastian",
        "Ben-Teoh": "Ben Teoh",
        "Benjamin-Berger": "Benjamin Berger",
        "Benjamin-Franklin": "Benjamin Franklin",
        "Benjammin-Halpern": "Benjammin Halpern",
        "Bennett-Muraskin": "Bennett Muraskin",
        "Benny-Andersson": "Benny Andersson",
        "Benoit-Mandelbrot": "Benoit Mandelbrot",
        "Berkman-Center-for-Internet-and-Society": "Berkman Center for Internet and Society",
        "Bernard-Cole": "Bernard Cole",
        "Bernard-Sachs": "Bernard Sachs",
        "Bernice-E-Rogowitz": "Bernice E Rogowitz",
        "Beth-Skwarecki": "Beth Skwarecki",
        "Betsy-Mason": "Betsy Mason",
        "Beáta-Megyesi": "Beáta Megyesi",
        "Bianca-Bickmore": "Bianca Bickmore",
        "Big-Ear": "Big Ear",
        "Big-Mess-o'-Wires": "Big Mess O’ Wires",
        "Big-Mess-o-Wires": "Big Mess O’ Wires",
        "Bill-C-13": "Bill C-13",
        "Bill-Chappell": "Bill Chappell",
        "Bill-Dana": "Bill Dana",
        "Bill-Etra": "Bill Etra",
        "Bill-Fernandez": "Bill Fernandez",
        "Bill-Gates": "Bill Gates",
        "Bill-Gross": "Bill Gross",
        "Bill-Hammack": "Bill Hammack",
        "Bill-Laumeister": "Bill Laumeister",
        "Bill-Martens": "Bill Martens",
        "Bill-Mensch": "Bill Mensch",
        "Bill-Moggridge": "Bill Moggridge",
        "Bill-Rankin": "Bill Rankin",
        "Bill-S-4": "Bill S-4",
        "Bill-Sweetman": "Bill Sweetman",
        "Bill-Watterson": "Bill Watterson",
        "Biology-Letters": "Biology Letters",
        "Bishop-Fox": "Bishop Fox",
        "Bjork": "Björk",
        "Black-Hat": "Black Hat",
        "Black-Sea-Fleet": "Black Sea Fleet",
        "Blade-Runner": "Blade Runner",
        "Blayne-Kinart": "Blayne Kinart",
        "Bloomberg-New-Energy-Finance": "Bloomberg New Energy Finance",
        "Bluetooth-4.0": "Bluetooth 4.0",
        "Bluetooth-LE": "Bluetooth LE",
        "Bob-Adams": "Bob Adams",
        "Bob-F-Burns": "Bob F Burns",
        "Bob-Farquhar": "Bob Farquhar",
        "Bob-Moog": "Bob Moog",
        "Bob-Moog-Foundation": "Bob Moog Foundation",
        "Bob-Parks": "Bob Parks",
        "Bob-Pease": "Bob Pease",
        "Bob-Rae": "Bob Rae",
        "Boeing-777": "Boeing 777",
        "Boeing-787": "Boeing 787",
        "Boeing-787-BCU": "Boeing 787 BCU",
        "Boise-State-University": "Boise State University",
        "Bonnie-Berkowitz": "Bonnie Berkowitz",
        "Border-Security": "Border Security",
        "Bored-Panda": "Bored Panda",
        "Bosch-Group": "Bosch Group",
        "Bose-Corporation": "Bose Corporation",
        "Boston-University": "Boston University",
        "Boulevard-du-Temple": "Boulevard du Temple",
        "Bovine-Growth-Hormone": "Bovine Growth Hormone",
        "Brad-Alles": "Brad Alles",
        "Bradley-Munkowitz": "Bradley Munkowitz",
        "Brainobrain-Jumeira-Child-Development-Program": "Brainobrain Jumeira Child Development Program",
        "Branding-Served": "Branding Served",
        "Brandon-Keim": "Brandon Keim",
        "Brandon-Wilson": "Brandon Wilson",
        "Brendan-Gregg": "Brendan Gregg",
        "Brewster-Kahle": "Brewster Kahle",
        "Brian-Barrett": "Brian Barrett",
        "Brian-Benchoff": "Brian Benchoff",
        "Brian-Fuller": "Brian Fuller",
        "Brian-Heater": "Brian Heater",
        " Brian-Joseph-Davis": "Brian Joseph Davis",
        "Brian-Knappenberger": "Brian Knappenberger",
        "Brian-Min": "Brian Min",
        "Brian-Perrett": "Brian Perrett",
        "Brian-Reimer": "Brian Reimer",
        "Brian-Silverman": "Brian Silverman",
        "Brian-Weinstein": "Brian Weinstein",
        "Brian-Wiser": "Brian Wiser",
        "BrickFair-2013": "BrickFair 2013",
        "British-Columbia": "British Columbia",
        "British-Transport-Films": "British Transport Films",
        "Brownian-noise": "Brownian noise",
        "Bruce-Carpenter": "Bruce Carpenter",
        "Bruce-Davis": "Bruce Davis",
        "Bruce-Haack": "Bruce Haack",
        "Bruce-Odland": "Bruce Odland",
        "Bruce-Reimer": "Bruce Reimer",
        "Bruce-Schneier": "Bruce Schneier",
        "Bruce-Sterling": "Bruce Sterling",
        "Bruce-Trump": "Bruce Trump",
        "Brutal-Deluxe-Software": "Brutal Deluxe Software",
        "Bryan-Pijanowski": "Bryan Pijanowski",
        "Bryon-Elliott": "Bryon Elliott",
        "Buchla-and-Associates": "Buchla and Associates",
        "Buckminster-Fuller": "Buckminster Fuller",
        "Bud-Cort": "Bud Cort",
        "Budweiser-Gardens": "Budweiser Gardens",
        "Bunnie Huang": "Andrew Bunnie Huang",
        "Bureau-of-American-Ethnology": "Bureau of American Ethnology",
        "Burgess-Shale": "Burgess Shale",
        "Burr-Settles": "Burr Settles",
        "Buster-Hein": "Buster Hein",
        "Butterfly-Labs": "Butterfly Labs",
        "Byte-Magazine": "Byte Magazine",


        "cbc": "CBC",
        "CA-Technologies": "CA Technologies",
        "CCC-2013": "30C3",
        "CFS-ALERT": "CFS Alert",
        "CHES-2014": "CHES 2014",
        "CN-Turbo": "CN Turbo",
        "COLORS-Magazine": "COLORS Magazine",
        "COLORS-News-Machine": "COLORS News Machine",
        "CPS-Emitron": "CPS Emitron",
        "CS221-Introduction-to-AI": "CS221 Introduction to AI",
        "CTL-Electronics": "CTL Electronics",
        "CUDA-Python": "CUDA Python",
        "Cailen-Dye": "Cailen Dye",
        "Caitlin-Rosenthal": "Caitlin Rosenthal",
        "Caity-Weaver": "Caity Weaver",
        "Caleb-Kraft": "Caleb Kraft",
        "Call-The-Office": "Call The Office",
        "CallText-5010": "CallText 5010",
        "Calvin-and-Hobbes": "Calvin and Hobbes",
        "Calyx-Institute": "Calyx Institute",
        "Cam-Davidson-Pilon": "Cameron Davidson-Pilon",
        "Camara-Miller": "Camara Miller",
        "Camila-Guarim": "Camila Guarim",
        "Canada-Border-Services-Agency": "Canada Border Services Agency",
        "Canada-Foundry-Company": "Canada Foundry Company",
        "Canada-Steamship-Lines": "Canada Steamship Lines",
        "Canadian-Centre-for-Policy-Alternatives-and-West-Coast-Environmental-Law": "Canadian Centre for Policy Alternatives and West Coast Environmental Law",
        "Canadian-Club": "Canadian Club",
        "Canadian-Forces": "Canadian Forces",
        "Canadian-Geographic": "Canadian Geographic",
        "Canadian-Military-History": "Canadian Military History",
        "Canadian-National-Railway": "Canadian National Railway",
        "Canadian-Press": "Canadian Press",
        "Canadian-Radio-television-and-Telecommunications-Commission": "Canadian Radio-television and Telecommunications Commission",
        "Canadian-Science-Writers'-Association": "Canadian Science Writers' Association",
        "Canary-Watch": "Canary Watch",
        "Canon-EOS-Rebel-T2i": "Canon EOS Rebel T2i",
        "Captain-Michael-Sawler": "Captain Michael Sawler",
        "Carl-Sagan": "Carl Sagan",
        "Carla-Diana": "Carla Diana",
        "Carla-Scaletti": "Carla Scaletti",
        "Carleton-University": "Carleton University",
        "Carmen-Ortiz": "Carmen Ortiz",
        "Carmen-Reinhart": "Carmen Reinhart",
        "Carnegie-Mellon-Computer-Club": "Carnegie Mellon University Computer Club",
        "Carnegie-Mellon-University": "Carnegie Mellon University",
        "Carol-Off": "Carol Off",
        "Carolyn-Humphreys": "Carolyn Humphreys",
        "Carolyn-Mathas": "Carolyn Mathas",
        "Carrie-Anne-Philbin": "Carrie Anne Philbin",
        "Carter-Baldwin": "Carter Baldwin",
        "Cartographies-of-Time": "Cartographies of Time",
        "Cassette-Tayble": "Cassette Tayble",
        "Castle-Group": "Castle Group",
        "Catherina-Fake": "Catherina Fake",
        "Catherine-Borgeson": "Catherine Borgeson",
        "Catholic-Church": "Catholic Church",
        "Center-for-Neural-and-Emergent-Systems": "Center for Neural and Emergent Systems",
        "Centigram-Communications": "Centigram Communications",
        "Centre-for-Social-Innovation": "Centre for Social Innovation",
        "Certain-Pictures": "Certain Pictures",
        "Chain-Home": "Chain Home",
        "Chain-Home-RDF": "Chain Home RDF",
        "Channel-101": "Channel 101",
        "Channel-4": "Channel 4",
        "Chao-Lin-Kuo": "Chao-Lin Kuo",
        "Chaos-Communication-Congress": "Chaos Communication Congress",
        "Chaos-Communication-Congress-2013": "Chaos Communication Congress 2013",
        "Chaos-Gorilla": "Chaos Gorilla",
        "Chaos-Monkey": "Chaos Monkey",
        "Charles-C-Royce": "Charles C Royce",
        "Charles-Chin-Yee": "Charles Chin Yee",
        "Charles-E-Leiserson": "Charles E Leiserson",
        "Charles-Eames": "Charles Eames",
        "Charles H. Townes": "Charles H Townes",
        "Charles-Kitchin": "Charles Kitchin",
        "Charles M. Schwab": "Charles M Schwab",
        "Charles-Stankievech": "Charles Stankievech",
        "Charles-University": "Charles University",
        "Charles Van Stockum Jr": "Charles Van Stockum, Jr.",
        "Charlie-Jane-Anders": "Charlie Jane Anders",
        "Chelsea-Vowel": "Chelsea Vowel",
        "Chi-Tien-Lui": "Chi-Tien Lui",
        "Chicago-Tribune": "Chicago Tribune",
        "Chief-Patrick-Madahbee": "Chief Patrick Madahbee",
        "Chief-Theresa-Spence": "Chief Theresa Spence",
        "Chip-Gracey": "Chip Gracey",
        "Chip-Quik": "Chip Quik",
        "Chloe-Stamper": "Chloe Stamper",
        "Chris-Bateman": "Chris Bateman",
        "Chris-Brigham": "Chris Brigham",
        "Chris-Burden": "Chris Burden",
        "Chris-Edwards": "Chris Edwards",
        "Chris-Gordon": "Chris Gordon",
        "Chris-Hulls": "Chris Hulls",
        "Chris-McVeigh": "Chris McVeigh",
        "Chris-Velazco": "Chris Velazco",
        "Chris-Wood": "Chris Wood",
        "Chris-Wysopol": "Chris Wysopol",
        "Chrissie-Hynde": "Chrissie Hynde",
        "Christian-Giroux": "Christian Giroux",
        "Christiane-Schaefer": "Christiane Schaefer",
        "Christina-Cheung": "Christina Cheung",
        "Christine-Cynn": "Christine Cynn",
        "ChristineElizabeth-Parsons-Dudley": "Christine Elizabeth Parsons-Dudley",
        "Christmas-Eve": "Christmas Eve",
        "Christoph-Gunkel": "Christoph Gunkel",
        "Christopher-Alexander": "Christopher Alexander",
        "Christopher K. Kovach": "Christopher K Kovach",
        "Christopher-Parsons": "Christopher Parsons",
        "Christopher-Riley": "Christopher Riley",
        "Christopher-Seufert": "Christopher Seufert",
        "Chuck-Peddle": "Chuck Peddle",
        "Church-of-Sant’Antonin": "Church of Sant’Antonin",
        "Cindy-Knight": "Cindy Knight",
        "Circuit-Cellar": "Circuit Cellar",
        "Circuit-Stickers": "Circuit Stickers",
        "Circuits-and-Electronics": "Circuits and Electronics",
        "Citizen-Lab": "Citizen Lab",
        "Citizen-Scientists-League": "Citizen Scientists League",
        "City-Planning": "City Planning",
        "City-Prints": "City Prints",
        "City-Sound-Inertia": "City Sound Inertia",
        "City-of-Toronto": "City of Toronto",
        "Civic-Commons": "Civic Commons",
        "Clara-Rockmore": "Clara Rockmore",
        "Clare-Beavan": "Clare Beavan",
        "Clare-O'Connor": "Clare O'Connor",
        "Class-Central": "Class Central",
        "Classic-Computing": "Classic Computing",
        "Claude-E-Shannon": "Claude E Shannon",
        "Claudia-Hammond": "Claudia Hammond",
        "Claudio-Saunt": "Claudio Saunt",
        "Clavia-Nordbeat": "Clavia Nordbeat",
        "Clayton-Shonkwiler": "Clayton Shonkwiler",
        "Clifford-Berry": "Clifford Berry",
        "Clifford-Stein": "Clifford Stein",
        "Clifford-Thurber": "Clifford Thurber",
        "Clive-Maxfield": "Clive Maxfield",
        "Clostridium-perfringens": "Clostridium perfringens",
        "Clostridium-perfringens-type-B": "Clostridium perfringens type B",
        "Club-Orlov": "Club Orlov",
        "Co-Design": "Co. Design",
        "Co.Design": "Co. Design",
        "CoCo-2": "CoCo 2",
        "CoCo-3": "CoCo 3",
        "Coat-of-Arms": "Coat of Arms",
        "Cocialism": "Socialism",
        "Cognitive-Assistant-that-Learns-and-Organizes": "Cognitive Assistant that Learns and Organizes",
        "Colin-Lecher": "Colin Lecher",
        "Colin-Marshall": "Colin Marshall",
        "Colin-Mitchell": "Colin Mitchell",
        "Colin-Novak": "Colin Novak",
        "Colin-Poitras": "Colin Poitras",
        "Colin-Wells": "Colin Wells",
        "Color-Computer-2": "Color Computer 2",
        "Color-Computer-3": "Color Computer 3",
        "Colossal-Cave": "Colossal Cave",
        "Colossal-Cave-Adventure": "Colossal Cave Adventure",
        "Colour-Chaser": "Colour Chaser",
        "Colour-Rendering-Index": "Colour Rendering Index",
        "Comerica-Park": "Comerica Park",
        "Commodore-64": "Commodore 64",
        "Commodore-Amiga": "Commodore Amiga",
        "Commodore-PET": "Commodore PET",
        "Commodore-USA": "Commodore USA",
        "Communications-of-the-ACM": "Communications of the ACM",
        "Computer-Virus-Catalog": "Computer Virus Catalog",
        "Conor-Friedersdorf": "Conor Friedersdorf",
        "Consumers-Distributing": "Consumers Distributing",
        "Continuum-Analytics-Inc": "Continuum Analytics Inc.",
        "Cooking-For-Engineers": "Cooking For Engineers",
        "Cooking-Hacks": "Cooking Hacks",
        "Copy-II+": "Copy II+",
        "Cornell-University-Library": "Cornell University Library",
        "Corps-of-Engineers": "Corps of Engineers",
        "Cortex-M0+": "ARM Cortex-M0+",
        "Cortex-M3": "ARM Cortex-M3",
        "Cory-Arcangel": "Cory Arcangel",
        "Cosmic-AC": "Cosmic AC",
        "Countdown-to-Zero": "Countdown to Zero",
        "Craig-Warner": "Craig Warner",
        "Crazyflie-Nano": "Crazyflie Nano",
        "Create-Digital-Music": "Create Digital Music",
        "Creative-Spaces": "Creative Spaces",
        "Cuban-missile-crisis": "Cuban missile crisis",
        "Cult-of-Mac": "Cult of Mac",
        "Cupid-curve": "Cupid curve",
        "Curtis-Electromusic-Systems": "Curtis Electromusic Systems",
        "Cypress-Semiconductor": "Cypress Semiconductor",
        "Cyril-Elwell": "Cyril Elwell",
        "Cyrus-Farivar": "Cyrus Farivar",


        "D-Esseni": "D Esseni",
        "D-Wave-Systems": "D-Wave Systems",
        "DARPA-Grand-Challenge": "DARPA Grand Challenge",
        "DC-Denison": "DC Denison",
        "DB-9": "DE-9",
        "DEF-CON": "DEF CON",
        "DEF-CON-20": "DEF CON 20",
        "DFU-mode": "DFU mode",
        "DHT-11": "DHT11",
        "DHT-22": "DHT22",
        "DISK_][": "Disk II",
        "DIY-Gamer-Kit": "DIY Gamer Kit",
        "DVI-Detective": "DVI Detective",
        "DVI-Detective-N": "DVI Detective N",
        "DVI-Detective-Plus": "DVI Detective Plus",
        "DX7": "Yamaha DX7",
        "Dag-Kittlaus": "Dag Kittlaus",
        "Daily-Intelligencer": "Daily Intelligencer",
        "Daily-Mail": "Daily Mail",
        "Damien-George": "Damien George",
        "Dan-Catt": "Dan Catt",
        "Dan-Colman": "Dan Colman",
        "Dan-Donovan": "Dan Donovan",
        "Dan-E-Burr": "Dan E Burr",
        "Dan-Heath": "Dan Heath",
        "Dan-Nosowitz": "Dan Nosowitz",
        "Dan-Pliskin": "Dan Pliskin",
        "Dan-Russell": "Dan Russell",
        "Dan-Smith": "Dan Smith",
        "Dangerous-Prototypes": "Dangerous Prototypes",
        "Daniel-A-Means": "Daniel A Means",
        "Daniel-Cooper": "Daniel Cooper",
        "Daniel-Dalton": "Daniel Dalton",
        "Daniel-Ellsberg": "Daniel Ellsberg",
        "Daniel-Genkin": "Daniel Genkin",
        "Daniel-McCallum": "Daniel McCallum",
        "Daniel-Roja": "Daniel Roja",
        "Daniel-Rosenberg": "Daniel Rosenberg",
        "Daniel-Sellers": "Daniel Sellers",
        "Daniel-Stoupin": "Daniel Stoupin",
        "Daniel-Terdiman": "Daniel Terdiman",
        "Daniel-Young": "Daniel Young",
        "Darcy-Burner": "Darcy Burner",
        "Dark-Energy": "Dark Energy",
        "Dark-Side-of-the-Moon": "Dark Side of the Moon",
        "Darla-Drake": "Darla Drake",
        "Darryl-Davies": "Darryl Davies",
        "Dartmouth-College": "Dartmouth College",
        "Data-Driven-Documents": "Data Driven Documents",
        "Dave-Ball": "Dave Ball",
        "Dave-Haynes": "Dave Haynes",
        "Dave-Jones": "Dave Jones",
        "Dave-Kendricken": "Dave Kendricken",
        "Dave-LeBlanc": "Dave LeBlanc",
        "Dave-O’Malley": "Dave O’Malley",
        "Dave-Rossum": "Dave Rossum",
        "Dave-Smith": "Dave Smith",
        "Dave-Smith-Instruments": "Dave Smith Instruments",
        " Dave-Thielking ": "Dave Thielking",
        "Dave-Thompson": "Dave Thompson",
        "Davenport-Works": "Davenport Works",
        "David-Barnett": "David Barnett",
        "David-Beazley": "David Beazley",
        "David-Bennun": "David Bennun",
        "David-Berhnholtz": "David Berhnholtz",
        "David-Byrne": "David Byrne",
        "David-Cuartielles": "David Cuartielles",
        "David-Friedman": "David Friedman",
        "David G. Andersen": "David G Andersen",
        "David-Gascón": "David Gascón",
        "David-Goldberg": "David Goldberg",
        "David-Gondek": "David Gondek",
        "David-Greelish": "David Greelish",
        "David-Hutton": "David Hutton",
        "David-Kushner": "David Kushner",
        "David-Lewandowski": "David Lewandowski",
        "David-Mason": "David Mason",
        "David-Miller": "David Miller",
        "David-Moore": "David Moore",
        "David-Rowan": "David Rowan",
        "David-S-F-Portree": "David S F Portree",
        "David-Shenk": "David Shenk",
        "David-Suzuki": "David Suzuki",
        "David W. Poole": "David W Poole",
        "David-Weinberger": "David Weinberger",
        "David-Zancai": "David Zancai",
        "David L. Kaplan": "David L Kaplan",
        "David L. Snyder": "David L Snyder",
        "Davis-Monthan-AFB": "Davis-Monthan AFB",
        "Debora-MacKenzie": "Debora MacKenzie",
        "Def-Con": "DEF CON",
        "DefCon": "DEF CON",
        "Defense-Advanced-Research-Projects-Agency": "Defense Advanced Research Projects Agency",
        "Delia-Derbyshire": "Delia Derbyshire",
        "Democracy-Now": "Democracy Now",
        "Denise-Ngo": "Denise Ngo",
        "Dennis-Klatt": "Dennis Klatt",
        "Dennis-Lacarruba": "Dennis Lacarruba",
        "Dennis-Overbye": "Dennis Overbye",
        "Department-of-Foreign-Affairs": "Department of Foreign Affairs",
        "Depeche-Mode": "Depeche Mode",
        "Derek-Ross": "Derek Ross",
        "Design-Plus-Occupy": "Design Plus Occupy",
        "Design-School": "Design School",
        "DesignTaxi": "DesignTAXI",
        "Designing-Interactions": "Designing Interactions",
        "Designing-Media": "Designing Media",
        "Destiny-laboratory": "Destiny laboratory",
        "Detroit-Tigers": "Detroit Tigers",
        "Dexter-Industries": "Dexter Industries",
        "Dexter-Payne": "Dexter Payne",
        "Diagon-Alley": "Diagon Alley",
        "Diemut-Strebe": "Diemut Strebe",
        "Dieter-Doepfer": "Dieter Doepfer",
        "Dietmar-Eckell": "Dietmar Eckell",
        "DigiKey": "Digi-Key",
        "Digilent-Analog-Discovery": "Digilent Analog Discovery",
        "Digital-Domain": "Digital Domain",
        "Digital-Journal": "Digital Journal",
        "Digital-Lovers-Blog": "Digital Lovers Blog",
        "Digital-Photography-Review": "Digital Photography Review",
        "Digital-Suburban": "Digital Suburban",
        "Digital Millennium Copyright Act of 1998": "Digital Millennium Copyright Act",
        "Dileep-George": "Dileep George",
        "Dirksen-Liu": "Dirksen Liu",
        "Disco-Dirge": "Disco Dirge",
        "Distributed-Impact-Detection-System": "Distributed Impact Detection System",
        "Dive-Into-Python": "Dive Into Python",
        "Dmitry-Orlov": "Dmitry Orlov",
        "Do-Not-Track": "Do Not Track",
        "Dodd-Frank-act": "Dodd-Frank Wall Street Reform and Consumer Protection Act",
        "Dolby-Atmos": "Dolby Atmos",
        "Dolphin-House": "Dolphin House",
        "Dolphin-Project": "Dolphin Project",
        "Dominion-Radiator-Company": "Dominion Radiator Company",
        "Don't-Go-Back-To-School": "Don't Go Back To School",
        "Don-Buchla": "Don Buchla",
        "Don-Sauer": "Don Sauer",
        "Donald-Weston": "Donald Weston",
        "Donna-Gustafson": "Donna Gustafson",
        "Doris-Norton": "Doris Norton",
        "Dorothy-Tan": "Dorothy Tan",
        "Doug-W-Mclntyre": "Doug W Mclntyre",
        "Doug-Woolridge": "Doug Woolridge",
        "Doug Engelbart": "Douglas Engelbart",
        "Douglas-Brooks": "Douglas Brooks",
        "Douglas-Main": "Douglas Main",
        "Douglas-Marting": "Douglas Marting",
        "Dow-Chemical": "Dow Chemical",
        "Dr-Eric-Leuthardt": "Dr. Eric Leuthardt",
        "Dr-John-Money": "Dr. John Money",
        "Dr-Mark-Robinson": "Dr. Mark Robinson",
        "Dr-Sam-Aaron": "Dr. Sam Aaron",
        "Dr-Shiv-Chopra": "Dr. Shiv Chopra",
        "Dragos-Ruiu": "Dragos Ruiu",
        "Drake-equation": "Drake equation",
        "Drobo-5N": "Drobo 5N",
        "Duffing-equation": "Duffing equation",
        "Duffing-oscillator": "Duffing oscillator",
        "Duke-University": "Duke University",
        "Duncan-Geere": "Duncan Geere",
        "Duncan-Macleod": "Duncan Macleod",
        "Dylan-McGrath": "Dylan McGrath",


        "École-Polytechnique-Fédérale-de-Lausanne": "École Polytechnique Fédérale de Lausanne",
        "Edward Tufe": "Edward Tufte",
        "E-MU": "E-Mu",
        "E-mu": "E-Mu",
        "E-mu-Systems": "E-Mu Systems",
        "E-mu Vintage Keys": "E-Mu Vintage Keys",
        "E-mu Vintage Keys Plus": "E-Mu Vintage Keys Plus",
        "E.D.W.-Lynch": "E D W Lynch",
        "EDW-Lynch": "E D W Lynch",
        "E. O. Wilson": "E O Wilson",
        "EE-Life": "EE Life",
        "EE-Times": "EE Times",
        "EE-Tips": "EE Tips",
        "ENIAC-Programmers-Project": "ENIAC Programmers Project",
        "ESRI-Shapefile": "ESRI Shapefile",
        "Eames-Lounge-Chair": "Eames Lounge Chair",
        "Eames-Ottoman": "Eames Ottoman",
        "Earl-F-Glynn": "Earl F Glynn",
        "Earth-We-are-one": "Earth. We are one.",
        "Easel-JS": "EaselJS",
        "Eastern-Grey-Squirrel": "Eastern Grey Squirrel",
        "Eclipse-RCP": "Eclipse RCP",
        "Ed-Borden": "Ed Borden",
        "Ed-Conroy": "Ed Conroy",
        "Ed-Roberts": "Ed Roberts",
        "Ed-Rotberg": "Ed Rotberg",
        "Ed-Stoppard": "Ed Stoppard",
        "Ed-Yong": "Ed Yong",
        "Edmonton-Sun": "Edmonton Sun",
        "Edward-Gorey": "Edward Gorey",
        "Edward-Greenspon": "Edward Greenspon",
        "Edward-Snowden": "Edward Snowden",
        "Edwards-Air-Force-Base": "Edwards Air Force Base",
        "Edwards-Airforce-Base": "Edwards Air Force Base",
        "Edwin-Abbott-Abbott": "Edwin Abbott Abbott",
        "Edwin-E-Aldrin": "Edwin E Aldrin",
        "Egan-Ford": "Egan Ford",
        "Eileen A. Joy": "Eileen A Joy",
        "Einstürzende-Neubauten": "Einstürzende Neubauten",
        "Ela-Darling": "Ela Darling",
        "Electric-Dreams": "Electric Dreams",
        "Electric-Druid": "Electric Druid",
        "Electrical-Construction-and-Maintenance": "Electrical Construction and Maintenance",
        "Electronic-Design": "Electronic Design",
        "Electronic-Frontier-Foundation": "Electronic Frontier Foundation",
        "Electronic-Melodist": "Electronic Melodist",
        "Elgin-Military-Museum-of-Naval-History": "Elgin Military Museum of Naval History",
        "Elgin-Park": "Elgin Park",
        "Eliane-Radigue": "Eliane Radigue",
        "Elizabeth-Perez": "Elizabeth Perez",
        "Ellie-Kirzner": "Ellie Kirzner",
        "Elliott-wave-principle": "Elliott wave principle",
        "Elon-Musk": "Elon Musk",
        "Eltro-Mark-II": "Eltro Mark II",
        "Eltro-Mark-II-Information-Rate-Changer": "Eltro Mark II Information Rate Changer",
        "Elvis-Presley": "Elvis Presley",
        "Elwyn-Berlekamp": "Elwyn Berlekamp",
        "Elísabet-Grétarsdóttir": "Elísabet Grétarsdóttir",
        "Embrace-Cinema-Gear-USA-LLC": "Embrace Cinema Gear USA LLC",
        "Emil-Schult": "Emil Schult",
        "Emily-Gertz": "Emily Gertz",
        "Emily-Haines": "Emily Haines",
        "Emily-Lakdawalla": "Emily Lakdawalla",
        "Emily Finn": "Emily S Finn",
        "Emma G. Fitzsimmons": "Emma G Fitzsimmons",
        "Emmanuel-Goldstein": "Emmanuel Goldstein",
        "Encyclopedia-of-Electronic-Components-Vol-1": "Encyclopedia of Electronic Components Vol 1",
        "Enigma-World-Code-Group": "Enigma World Code Group",
        "Eran-Tromer": "Eran Tromer",
        "Erdem-Gunduz": "Erdem Gunduz",
        "Eric-Bogatin": "Eric Bogatin",
        "Eric-Dunham": "Eric Dunham",
        "Eric-Harshbarger": "Eric Harshbarger",
        "Eric-Ladizinsky": "Eric Ladizinsky",
        "Eric-M-Dunham": "Eric M Dunham",
        "Eric-Madaras": "Eric Madaras",
        "Eric-Michaud": "Eric Michaud",
        "Eric-Petersen": "Eric Petersen",
        "Eric-Ravenscraft": "Eric Ravenscraft",
        "Eric-Schmidt": "Eric Schmidt",
        "Eric-Siegel": "Eric Siegel",
        "Eric-Wahlforss": "Eric Wahlforss",
        "Eric Melrose Brown": '''Eric Melrose “Winkle” Brown''',
        '''Eric Melrose “Winkle” Brown''': '''Eric Melrose “Winkle” Brown''',
        '''Eric “Winkle” Brown''': '''Eric Melrose “Winkle” Brown''',
        "Eric Brown": '''Eric Melrose “Winkle” Brown''',
        "Erik-Voss": "Erik Voss",
        "Erik-Wernquist": "Erik Wernquist",
        "Erika-Moen": "Erika Moen",
        "Ernst-Werner-von-Siemens": "Ernst Werner von Siemens",
        "Errol-Morris": "Errol Morris",
        "Erwan-Xiao": "Erwan Xiao",
        "Eurofighter-Typhoon": "Eurofighter Typhoon",
        "European-Research-Council": "European Research Council",
        "European-Space-Administration": "European Space Agency",
        "Eva-Braun": "Eva Braun",
        "Evan-Ackerman": "Evan Ackerman",
        "Evan-Doorbell": "Evan Doorbell",
        "Evil-Mad-Scientist-Laboratories": "Evil Mad Scientist Laboratories",
        "Ewen-MacAskill": "Ewen MacAskill",
        "Existential-Comics": "Existential Comics",
        "Exit-2012": "Exit 2012",
        "Exploding-The-Phone": "Exploding The Phone",
        "Eye-Ball": "Eye Ball",
        "Eye-Ball!": "Eye Ball",
        "Ezra-Hilyer": "Ezra Hilyer",


        "F-Forsberg": "F Forsberg",
        "F-M-Einheit": "F M Einheit",
        "F-Niklaus": "F Niklaus",
        "F.-Roemhild": "F Roemhild",
        "FCC-ID": "FCC ID",
        "FCC-ID-search": "FCC ID search",
        "FM-radio": "FM radio",
        "FPGA-Synth": "FPGA Synth",
        "Fabrizio-Carbone": "Fabrizio Carbone",
        "Facebook-Graph-Search": "Facebook Graph Search",
        "Faisal-Hoque": "Faisal Hoque",
        "Fanabriques-2012": "Fanabriques 2012",
        "Fantod-Pack": "Fantod Pack",
        "Faraday-shield": "Faraday shield",
        "Farah_Halime": "Farah Halime",
        "Fearghal-O'dea": "Fearghal O'dea",
        "Federal-Accountability-Initiative-for-Reform": "Federal Accountability Initiative for Reform",
        "Federal-Communications-Commission": "Federal Communications Commission",
        "Federal-Telegraph-Company": "Federal Telegraph Company",
        "Federal-Trade-Commission": "Federal Trade Commission",
        "Felix-Baumgartner": "Felix Baumgartner",
        "Feynman-diagram": "Feynman diagram",
        "Fibonacci-number": "Fibonacci number",
        "Fibonacci-retracement": "Fibonacci retracement",
        "Fibonacci-sequence": "Fibonacci sequence",
        "Fibonacci-series": "Fibonacci series",
        "Filippo-Scognamiglio": "Filippo Scognamiglio",
        "Fiorenzo G. Omenetto": "Fiorenzo G Omenetto",
        "Fiorenzo Omenetto": "Fiorenzo G Omenetto",
        "Fireside-Al": "Fireside Al",
        "Flash-Emulation-Tool": "Flash Emulation Tool",
        "Fletcher-Burwell-Taylor": "Fletcher Burwell-Taylor",
        "Fletcher-Capstan-Table": "Fletcher Capstan Table",
        "Florian-Schneider": "Florian Schneider",
        "Force-Four-Entertainment": "Force Four Entertainment",
        "Ford-Motor-Company-of-Canada": "Ford Motor Company of Canada",
        "Forest-King": "Forest King",
        "Fort-Sumter": "Fort Sumter",
        "Found-Functions": "Found Functions",
        "Fourier's-Law": "Fourier's Law",
        "Fourier-series": "Fourier series",
        "Fourier-transform": "Fourier transform",
        "Fouriest-Series": "Fourier series",
        "Frances-Bilas-Spence": "Frances Bilas Spence",
        "Frances-Elizabeth-Holberton": "Frances Elizabeth Holberton",
        "Francie-Diep": "Francie Diep",
        "Frank-Drake": "Frank Drake",
        "Frank-Feltman": "Frank Feltman",
        "Frank-van-der-Stappen": "Frank van der Stappen",
        "Frankie-Goes-to-Hollywood": "Frankie Goes to Hollywood",
        "Franklin-Delano-Roosevelt": "Franklin Delano Roosevelt",
        "Fred-Hoyle": "Fred Hoyle",
        "Fred-N-Baynes": "Fred N Baynes",
        "Fred-Terman": "Frederick Terman",
        "Frederic-Brun": "Frederic Brun",
        "Frederick-Forsyth": "Frederick Forsyth",
        "Frederick P. Brooks Jr.": "Frederick P Brooks Jr.",
        "Free-Music-Archive": "Free Music Archive",
        "Free-Software": "Free Software",
        "Freedom-of-the-Press-Foundation": "Freedom of the Press Foundation",
        "Freescale-Semiconductor": "Freescale Semiconductor",
        "Friedrich-August-von-Veltheim": "Friedrich August von Veltheim",
        "Friedrich-Nietzsche": "Friedrich Nietzsche",
        "Friedrich L. Bauer": "Friedrich L Bauer",
        "Frozen-Raspberry": "Frozen Raspberry",
        "Full-Circle-Magazine": "Full Circle Magazine",
        "Futility-Closet": "Futility Closet",
        "Future-Electronics": "Future Electronics",


        "GIS-Lounge": "GIS Lounge",
        "GNU-Linux": "GNU/Linux",
        "GNU-Make": "GNU Make",
        "GPL-3": "GPLv3",
        "GReat-Images-in-NASA": "GReat Images in NASA",
        "Gabor-Maté": "Gabor Maté",
        "Gabriel-Tremblay": "Gabriel Tremblay",
        "Gail-Chiasson": "Gail Chiasson",
        "Galatic-AC": "Galatic AC",
        "Galloway-Forest-Park": "Galloway Forest Park",
        "Gary-Grosse": "Gary Grosse",
        "Gaussian-distribution": "Gaussian distribution",
        "Gaussian-noise": "Gaussian noise",
        "Gavin-J-Rothery": "Gavin J Rothery",
        "Geeta-Dayal": "Geeta Dayal",
        "Geiger-counter": "Geiger counter",
        "Geiger–Müller-tube": "Geiger–Müller tube",
        "Geminoid-DK": "Geminoid DK",
        "Gene-Radzik": "Gene Radzik",
        "Gene-Siskel": "Gene Siskel",
        "General-Suharto": "General Suharto",
        "General-Dynamics": "General Dynamics",
        "General-Dynamics-Astronautics": "General Dynamics Astronautics",
        "General-Electric": "General Electric",
        "General-Electric-Davenport-Works": "General Electric Davenport Works",
        "General-John-J-Pershing": "General John J Pershing",
        "Genesis-P-Orridge": "Genesis P-Orridge",
        "GeoReport-v1": "GeoReport v1",
        "GeoReport-v2": "GeoReport v2",
        "Geodatabase-file": "Geodatabase file",
        "Geoff-Bartlett": "Geoff Bartlett",
        "Geoff-Campbell": "Geoff Campbell",
        "Geoffrey A. Fowler": "Geoffrey A Fowler",
        "Georg-Duffing": "Georg Duffing",
        "George-Dvorsky": "George Dvorsky",
        "George-Henton": "George Henton",
        "George-Sanger": "George Sanger",
        "George-Vaillant": "George Vaillant",
        "Georgetown-South-Project": "Georgetown South Project",
        "Georgi-Grechko": "Georgi Grechko",
        "Gerald-Sussman": "Gerald Sussman",
        "Gerard-Lambert": "Gerard Lambert",
        "German-Research-Foundation": "German Research Foundation",
        "Germinio-Politi": "Germinio Politi",
        "Geroges-Seurat": "Georges Seurat",
        "Gerry-O’Brien": "Gerry O’Brien",
        "Ghosts-in-the-Machine": "Ghosts in the Machine",
        "Gibraltar-Point-Light-House": "Gibraltar Point Light House",
        "Gibson-Research-Corporation": "Gibson Research Corporation",
        "Giordano-Ciampini": "Giordano Ciampini",
        "Gisele-Muller": "Gisele Muller",
        "Gislain-Benoit": "Gislain Benoit",
        "Glenn-Greenwald": "Glenn Greenwald",
        "Glenn-Rifkin": "Glenn Rifkin",
        "Global-Nerdy": "Global Nerdy",
        "Global-Soundscape-project": "Global Soundscape project",
        "Globe-and-Mail": "Globe and Mail",
        "Godtfred-Kirk-Christiansen": "Godtfred Kirk Christiansen",
        "Goli-Mohammadi": "Goli Mohammadi",
        "Google-Brain": "Google Brain",
        "Google-Chrome": "Google Chrome",
        "Google-Cloud-Platform-Developer-Relations-team": "Google Cloud Platform Developer Relations team",
        "Google-Docs": "Google Docs",
        "Google-Lat-Long": "Google Lat Long",
        "Google-Maps": "Google Maps",
        "Google-Maps-Street-View": "Google Maps Street View",
        "Google-Now": "Google Now",
        "Google-X": "Google X",
        "Governor-General": "Governor General",
        "Grace-Allison": "Grace Allison",
        "Grace-Jones": "Grace Jones",
        "Gracey-and-Associates": "Gracey and Associates",
        "Graeme-Bayliss": "Graeme Bayliss",
        "Graham-Burnett": "Graham Burnett",
        "Graham-Wallas": "Graham Wallas",
        "Grand-Council-Assembly": "Grand Council Assembly",
        "Grand-Council-Chief-John-Beaucage": "Grand Council Chief John Beaucage",
        "Grant-Nelson": "Grant Nelson",
        "Grant-Searle": "Grant Searle",
        "Graphing-Calculator": "Graphing Calculator",
        "Gray-code": "Gray code",
        "Great-Barrier-Reef": "Great Barrier Reef",
        "Great-Enlightened-Society-of-Oculists": "Great Enlightened Society of Oculists",
        "Great-Innovations": "Great Innovations",
        "Great-Temple-of-Jerusalem": "Great Temple of Jerusalem",
        "Green-Button": "Green Button",
        "GreenOwl-Mobile": "GreenOwl Mobile",
        "Greenfield-Village": "Greenfield Village",
        " Greenfield-Village": "Greenfield Village",
        "Greg-James": "Greg James",
        "Greg-Robbins": "Greg Robbins",
        "Greg-Wilson": "Greg Wilson",
        "Gregory-Bateson": "Gregory Bateson",
        "Gregory-Ferenstein": "Gregory Ferenstein",
        "Grid-Compass": "Grid Compass",
        "Groom-Lake": "Groom Lake",
        "Grégoire-Ribordy": "Grégoire Ribordy",
        "Guiness-World-Records": "Guiness World Records",
        "Gustave-Solomon": "Gustave Solomon",
        "Gustavo-Castro": "Gustavo Castro",
        "Guy-Kawasaki": "Guy Kawasaki",
        "Gwen-Pearson": "Gwen Pearson",


        "H-R-Giger": "H R Giger,",
        "H. J. Heinz": "H J Heinz",
        "H. James Wilson": "H James Wilson",
        "HAM-radio": "HAM radio",
        "HD-video": "HD video",
        "HMCS-Ojibwa": "HMCS Ojibwa",
        "HP-5036A": "HP 5036A",
        "HP-5036A-Microprocessor-Lab": "HP 5036A Microprocessor Lab",
        "HRL-Laboratories-LLC": "HRL Laboratories LLC",
        "HTM-Cortical-Learning-Algorithms": "HTM Cortical Learning Algorithms",
        "Hack-a-Day": "Hackaday",
        "Hackers-Heroes-of-the-Computer-Revolution": "Hackers Heroes of the Computer Revolution",
        "Hackers-on-Planet-Earth": "Hackers on Planet Earth",
        "Hadi T. Nia": "Hadi T Nia",
        "Halifax-Stanfield-International-Airport": "Halifax Stanfield International Airport",
        "Hall-of-Fame": "Hall of Fame",
        "Halley-Docherty": "Halley Docherty",
        "Halt-and-Catch-Fire": "Halt and Catch Fire",
        "Hamilton-Gear-Company": "Hamilton Gear Company",
        "Hamutal-Dotan": "Hamutal Dotan",
        "Hand-Made-Music": "Hand Made Music",
        "Hangar-One": "Hangar One",
        "Hans-B-Thiessen": "Hans B Thiessen",
        "Hans-Camenzind": "Hans Camenzind",
        "Hans-Rudolf-Giger": "H R Giger",
        "Hanscom-Air-Force-Base": "Hanscom Air Force Base",
        "Hardware-Book": "Hardware Book",
        "Harold-R-Walker": "Harold R Walker",
        "Harry-Atwater": "Harry Atwater",
        "Harry-Bissell": "Harry Bissell",
        "Harry-Nyquist": "Harry Nyquist",
        "Harry-Potter": "Harry Potter",
        "Harvard-Smithsonian-Center-for-Astrophysics": "Harvard-Smithsonian Center for Astrophysics",
        "Hawk-missile-system": "Hawk missile system",
        "Health-Canada": "Health Canada",
        "Heath-Company": "Heath Company",
        "Heather-Brown": "Heather Brown",
        "Heathkit-OR-1": "Heathkit OR-1",
        "Heinz-History-Center": "Heinz History Center",
        "Henrik-Scharfe": "Henrik Scharfe",
        "Henry-Franks": "Henry Franks",
        "Henry-Goodman": "Henry Goodman",
        "Herbert A. Simon": "Herbert A Simon",
        "Herman-Miller": "Herman Miller",
        "Hermione-Granger": "Hermione Granger",




        "plone": "Plone",
        "python": "Python",


        "Tufte": "Edward Tufte",


        "white-hole": "white hole",
        "white-noise": "white noise",
        "white-nose_syndrome": "white-nose syndrome",
        "white-paper": "white paper",
        "white-squirrel": "white squirrel",
        "wideband-audio": "wideband audio",
        "wikibooks": "Wikibooks",
        "wikileaks": "WikiLeaks",
        "wikimedia": "Wikimedia",
        "wikinomics": "Wikinomics",
        "wikipedia": "Wikipedia",
        "wind-tunnel": "wind tunnel",
        "wire-to-the-ear": "Wire to the Ear",
        "wired-glove": "wired glove",
        "wireless-access-point": "wireless access point",
        "wireless-mesh-network": "wireless mesh network",
        "wireless-service-provider": "wireless service provider",
        "worplace": "workplace",
        "world-record": "world record",
        "world-wide-web": "World Wide Web",
        "woz": "Woz",
        "wwii": "WWII",
        "www": "WWW",


        "xhtml": "XHTML",
        "xml": "XML",
        "x-ray": "X-ray",


        "yacht-rock": "yacht rock",
        "yahoo": "Yahoo",
        "Yale_Univerity": "Yale University",
        "Yale_university": "Yale University",
        "yamaha": "Yamaha",
        "Yuri-Gagarin": "Yuri Gagarin",
        "Yuri-Malyshev": "Yuri Malyshev",


        "Zach-Weiner": "Zach Weiner",
        "Zachary-Cohen": "Zachary Cohen",
        "zbrush": "ZBrush",
        "zeppelin": "Zeppelin",
        "zero-energy-state": "zero energy state",
        "zeta-function": "zeta function",
        "ZigBee-IP": "ZigBee IP",
        "Zimmerli-Art-Museum": "Zimmerli Art Museum",
        "Zoom-H2N": "Zoom H2n",
        "zope": "ZOPE",
        "Zug-Island": "Zug Island",
    }

# source_filename = 'delicious_minimal.html'
source_filename = 'delicious.html'
source_filepath = os.path.join('.', 'tests', 'test_data', source_filename)

with open(source_filepath) as source_file:
    bookmarks = source_file.read()
    soup = BeautifulSoup(bookmarks, 'html.parser')
    links = soup.find_all('a')

    all_sanitized_tags = set()

    for link in links:
        href = link['href']
        tags = link['tags']
        # print(href)

        # Splits the comma-separated string of tags into a list
        split_tags = tags.split(',')
        # print(split_tags)

        # Sanitizes the tags, and adds each one to a set object, in order to eliminate any duplicates
        sanitized_tags = set()
        for tag in split_tags:
            sanitized_tag = tag_translations.get(tag, tag).strip().replace(' ', '_')
            sanitized_tags.add(sanitized_tag)
            all_sanitized_tags.add(sanitized_tag)
        # print(sanitized_tags)

    for sanitized_tag in sorted(all_sanitized_tags):
        print(sanitized_tag)
